title: "[游戏Id]游戏名称 {附加信息}"
body:
  - type: input
    id: appid
    attributes:
      label: "Steam 游戏ID"
    validations:
          required: true
  - type: input
    id: appName
    attributes:
      label: "Steam 游戏名称"
    validations:
          required: true  
  - type: textarea
    id: keys
    attributes:
      label: "密钥列表"
      placeholder: |
        depotid;depotkey
        depotid;depotkey
    render: hash
    validations:
        required: true
  - type: textarea
    id: manifests
    attributes:
      label: "清单附件"
    validations:
        required: true
   
